import Head from 'next/head'
import Navbar from "../components/Navbar";
import Centered from "../components/Centered";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>

            <Centered>
                <h1>Home page (todo)</h1>
            </Centered>
        </div>
    )
}
